/**
 * @file  Key of action will be listed here
 */

enum ActionTypeKeys {
    TOGGLE_MODAL = "TICKETING_PAGE/TOGGLE_MODAL",
    IS_SHOW_NEXT_BUTTON = "TICKETING_PAGE/IS_SHOW_NEXT_BUTTON",
    HANDLE_CHOOSE_SEATS = "TICKETING_PAGE/HANDLE_CHOOSE_SEATS",
    HANDLE_CHOOSE_FOODS = 'TICKETING_PAGE/HANDLE_CHOOSE_FOODS',
    GET_ALL_FOODS = 'TICKETING_PAGE/GET_ALL_FOODS',
    GET_ALL_FOODS_SUCCESS = 'TICKETING_PAGE/GET_ALL_FOODS_SUCCESS',
    GET_ALL_FOODS_FAIL = 'TICKETING_PAGE/GET_ALL_FOODS_FAIL',

    CONFIRM_PAYMENT = 'TICKETING_PAGE/CONFIRM_PAYMENT',

    CREATE_TICKET = 'TICKETING_PAGE/CREATE_TICKET',
    CONFIRM_PAYMENT_SUCCESS = 'TICKETING_PAGE/CONFIRM_PAYMENT_SUCCESS',


}

export default ActionTypeKeys;
