image: node:12.19.0-alpine

stages:
  - deploy

deploy_production:
  stage: deploy
  before_script:
    - apk add --update openssh sshpass git
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - ssh-keyscan gitlab.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
    - rm -rf .git
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "Building deploy package"
    - yarn install
    - yarn build
    - echo "Build successful"
  script:
    - echo "Deploying to server"
    - scp -r ./build root@staging.pawnpd.tk:/var/www/pawn-employee
    - ssh root@staging.pawnpd.tk "nginx -s reload"
    - echo "Deployed"
  only:
    - master
    - merge_requests