/**
 * @file  Key of action will be listed here
 */

enum ActionTypeKeys {
    TOGGLE_MODAL = "DETAILS_PAGE/TOGGLE_MODAL",

    GET_SESSION_BY_MOVIE_ID = 'DETAILS_PAGE/GET_SESSION_BY_MOVIE_ID',
    GET_SESSION_BY_MOVIE_ID_SUCCESS = 'DETAILS_PAGE/GET_SESSION_BY_MOVIE_ID_SUCCESS',
    GET_SESSION_BY_MOVIE_ID_FAIL = 'DETAILS_PAGE/GET_SESSION_BY_MOVIE_ID_FAIL',

    HANDLE_CLEAR_SESSION_RECORD = 'DETAILS_PAGE/HANDLE_CLEAR_SESSION_RECORD'

}

export default ActionTypeKeys;
