/**
 * @file  Key of action will be listed here
 */

enum ActionTypeKeys {
    HANDLE_CLEAR = "HOME_PAGE/HANDLE_CLEAR",
    
    TOGGLE_MODAL = "HOME_PAGE/TOGGLE_MODAL",

    GET_ALL_MOVIES = 'HOME_PAGE/GET_ALL_MOVIES',
	GET_ALL_MOVIES_SUCCESS = 'HOME_PAGE/GET_ALL_MOVIES_SUCCESS',
    GET_ALL_MOVIES_FAIL = 'HOME_PAGE/GET_ALL_MOVIES_FAIL',
    
    GET_MOVIES_BY_STATUS = 'HOME_PAGE/GET_MOVIES_BY_STATUS',
    GET_MOVIES_BY_STATUS_SUCCESS = 'HOME_PAGE/GET_MOVIES_BY_STATUS_SUCCESS',
    GET_MOVIES_BY_STATUS_FAIL = 'HOME_PAGE/GET_MOVIES_BY_STATUS_FAIL',

    HANDLE_CURRENT_MOVIE = 'HOME_PAGE/HANDLE_CURRENT_MOVIE',

}

export default ActionTypeKeys;
