/**
 * @file  Key of action will be listed here
 */

enum ActionTypeKeys {
    HANDLE_CLEAR = "LOGIN_PAGE/HANDLE_CLEAR",
    
    POST_EMPLOYEE_LOGIN = "LOGIN_PAGE/POST_EMPLOYEE_LOGIN",
    POST_EMPLOYEE_LOGIN_SUCCESS = "LOGIN_PAGE/POST_EMPLOYEE_LOGIN_SUCCESS",
    POST_EMPLOYEE_LOGIN_FAIL = "LOGIN_PAGE/POST_EMPLOYEE_LOGIN_FAIL",

    GET_PERMISSIONS = "LOGIN_PAGE/GET_PERMISSIONS",
    GET_PERMISSIONS_SUCCESS = "LOGIN_PAGE/GET_PERMISSIONS_SUCCESS",
    GET_PERMISSIONS_FAIL = "LOGIN_PAGE/GET_PERMISSIONS_FAIL",
}

export default ActionTypeKeys;
